[package]
name = "icn2037"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = "0.3"
embedded-graphics-core = "0.4.0"
embedded-hal = "1.0.0"
